### ISSUE TITLE
question and help about using in android

### ISSUE THREAD

**Issue by Hosseinyzr** [falahati1987/ffmpeg4Android#2]
Hi,Actually I have a question . ...
I wanna use ffmpeg in android (using android studio with java).
as i know there should be a wrapper for the libraries. I searched a repository . is this link useful for libs u put in ffmpeg-build folder?
[https://github.com/bytedeco/javacpp-presets/tree/master/ffmpeg](url)
........
and if it is OK , can you please help how to use them?

**Comment by d-fal** [comment]
I think you are asking a quite basic question. Read more about NDK, then come to me if you want any help.

**Comment by Hosseinyzr** [comment]
@falahati1987  actually i read about jni and ndk but unfortunately i still having problem...
i am searching for a solution how to use these libraries in android studio and do things with ffmpeg commands...
[https://github.com/WritingMinds/ffmpeg-android-java](url) i saw these repo  and i wonder if your pre builts can be used in it?
